### PR TITLE
 Add compatibility with Laravel 11

### PR DESCRIPTION
**Pull request by julienarcin**
Add compatibility with Laravel 11 and phpunit 10 (referring #76 ).
Tests should pass.

### CODE REVIEW

**Comment by julienarcin** [comment]
What do you think @kyranb ?

**Comment by julienarcin** [comment]
Bump @kyranb

**Comment by julienarcin** [comment]
Bump @kyranb

**Comment by julienarcin** [comment]
Bump @kyranb

**Comment by kyranb** [comment]
Sorry for the delay on this one! Thanks for sending this in :)

**Comment by tklaas** [comment]
is there a reason that no new release after 3.1.5 was added including Laravel 11 support?

**Comment by kyranb** [comment]
@tklaas No reason! Just created a new release now 👍

**Pull request merged**
