### PR TITLE
Releases/v3

### PR DESCRIPTION
**Pull request by bilfeldt**
- [x] Fixes minor bug about footprint being a pure function (introduced in #41 dammit!)
- [x] Now only supporting PHP7.4+ and Laravel7+
- [x] Delete unused Facade
- [x] Implement return type casting and typed properties
- [ ] Implement Github actions (stolen 100% from [https://github.com/spatie/laravel-http-logger](spatie/laravel-http-logger) 🙏 )
- [ ] Update Laravel version in package image @kyranb ?

### CODE REVIEW

**Comment by bilfeldt** [comment]
@kyranb I have added Github actions as you can see. If you enable this then I think we should see the tests for pull requests so that at least those few tests that are implemented are being tested 😆

**Review by kyranb — APPROVED** [review]

**Comment by bilfeldt** [comment]
@kyranb Do you need more from me before tagging a version 3?

**Comment by kyranb** [comment]
Maybe just a summary of the changelog and upgrades to post when I create the release in GitHub?

**Comment by bilfeldt** [comment]
@kyranb Summary draft:
Version 3 adds significant flexibility by using configurable interfaces that can be used to taylor the logic for almost any requirements. The release also makes it possible to track requests in situations where cookies are not an option. This is done by making a fingerprint of the users ip and the browsers user-agent.

Note that version 3 contains breaking change but a step-by-step upgrade guide has been made available [here](https://github.com/kyranb/Footprints/blob/master/README.md#2x--3x).

@kyranb Note that the header image still says "for Laravel 5.1+" which is no longer valid. Really looks forward to the release 👍

**Comment by kyranb** [comment]
Released: https://github.com/kyranb/Footprints/releases/tag/3.0

Thanks again for all of your contributions :)

**Pull request merged**
